package test:guest;

interface foo {
    use bar.{myresource};
    // Creates and uses a resource
    use-resource: func();
    // Creates and uses a resource
    consume-resource: func(a: myresource);
}

interface bar {
    resource myresource { 
        constructor(a: s32);
        print-a: func();
    }
}

world guest {
    export foo;
    import bar;
}